# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jeff Smith, PsyD
tagline:          'Psychotherapist & Writer'
description:      'Do not take yourself for granted. Listen carefully to what you think and articulate the truth that you know without resentment and without apology. See where the truth takes you.'
url:              http://jeffreygrantsmith.com
baseurl:          /

author:
  name:           'Jeff Smith'
  url:            https://twitter.com/smithjeffreyg

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
